#+TITLE:       2015新年总结
#+AUTHOR:      enzo liu
#+EMAIL:       liuenze6516@gmail.com
#+DATE:        2016-02-08 Mon
#+URI:         /blog/%y/%m/%d/2015新年总结
#+KEYWORDS:    总结, 2015
#+TAGS:        summary
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 2015 年度总结

农历新年第一天，实在有种冲动，知道自己前一年 =到底做了什么= ， 今年，又 =想达成什么= 。

于是，一大早，在拜完年后，安安静静的坐下，整理一下过去一年的生活。

* 结婚

/成家立业/ , 在27岁的这年，终于完成了 =结婚= 这件大事。 从03年初识，11年相恋, 15年结婚。 十几年一路走来，风景颇多。

从年初两家定好婚期，拍婚纱照，挑婚纱，邀请亲朋参加婚礼，买礼服，邀请好友来做伴郎伴娘，到和两地婚庆沟通婚礼事项，相互协调婚俗，最终收获了一个都很满意的仪式。


* 驾照

除了结婚，今年另外一项成就是终于把学车给搞定了。 工作中学车的辛苦就不多说了, ~出来混的，欠债总是要还。~

刚拿到驾照第一天，尝试租了一辆自动挡( /之前只学着开过手动/ ) 去接我老婆。那一路开的可真是心惊胆战。

还好老婆是老驾驶 +证+ 了, 在她的副驾监督下, 还走了几次4-6个小时的高速。周末偶尔出去自驾游，瞬间提升了不少幸福感。

* 跳槽

11年毕业，13年下半年来到了上海，就待在点评。今年，开始对自己的工作状态和长进不甚满意。于是在8月份跳槽去了一家小创业公司。

从无到有的感觉非常棒。

从裸的一台服务器，到内网完整的开发，测试，发布环境。
从kvm虚拟化, 到网络规划，到安装 ~gitlab~, ~jenkins~, ~artifactory~ 等。
从一个想象中的产品，到一个线上运行，最多日均流水到了几十万的小应用。

尽管前途未卜，但这一路的风光也应该可以不虚此行吧。

* 技能

技能上没有什么本质的变化。上一次本质的变化还是分别在读了 =sicp= , =learn you a haskell for great good!= 之后。

/16年的一个大的任务就是系统性的整理一下自己技能体系。/

** 满意的项目

一个利用java的 =annotation processor=, 在编译期，在mybatis框架下，根据 =mapper 名称= 自动生成对应sql的小工具。

做的事情很简单，但是的确可以减少一部分信息的冗余，也减少了自己的开发工作，感觉很好。

** 新增技能

- ansible :: 运维脚本: 打包，上传，发布，重启等一整套流程
- scala? :: 后台系统的开发, 可惜用的太浅
- angular? :: 同上

* 阅读

买了一个看书神器 =dps-s1=

** 技术类

读了一半，读完还是挺累的，16年继续...

- computer system , a programmer's perspectvie
- steps toward artificial intelligence

** 半技术类

- growth hacker
- zero to one
- doom 启示录
- 软件随想录

** 小说类

- 基地 (1-6)

* 旅游

** 无锡
** 海南
** 千岛湖
** 香港

*  [TODO] 明年计划

** 工作

** 旅游

** 个人提升

** [maybe] 生子
