#+TITLE: 如何设计一个业务系统
#+AUTHOR: 刘恩泽
#+EMAIL:  enze.liu@ipiaoniu.com
#+DATE: 2018-06-04
#+OPTIONS:   H:3 toc:t num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LaTeX_CLASS: article
#+LATEX_HEADER: \renewcommand*{\contentsname}{目录}

* 本文的目的
1. 希望能对设计过程有一个整体的概念
2. 希望能够参照这个过程，完成一些简单的业务系统设计
3. 本文重点针对于业务系统设计和分析。不太涉及系统设计的其他方面，如性能，可靠，可见等等。

PS:
- 也希望业务系统设计不再会是个人发展的瓶颈

* 背景

现阶段，对人员的需求已经不再是能有一个简单的需求把做出来。更可能是能独立承接一个有点复杂的需求。比如拼团，比如加速包, 比如套票。有一个略微复杂的流程，有更多的场景，涉及到更多的状态和角色和交互。

在这种情况下，按照以往直接想想就开始做的方式，已经很难得心应手的把东西做出来了。经常会遇到:
- 做了一半，感觉好像不太对
- 写着写着写不下去了
- 怎么写都有些地方考虑不周到

在我来看，缺的就是一个设计的过程:
- 如何在不同的角度去分析这个需求
- 如何将一个复杂的问题拆解成几个更小的子问题
- 如何将一个不是很复杂的子问题落实到模块/代码中

过去也会写好一个设计文档, 再和大家去讲, 但是效果感觉并没有很好。借着这次拼团的系统，希望能把这个过程剖析的更具体一些, 看看是否能给大家更多的助益。

* 设计的目的

*为什么要设计?*,
- 因为不设计已经做不下去了。

评估一个设计的好坏，就看能否清晰的表达出 *要做什么* ， *怎么做* ， *为什么要这么做* 。

*为什么要详细的设计?*, 在用户流程，模块，复杂对象的生命周期等不同的维度分别做设计。
- 因为脑力有限，无法同时关注这么多的细节，所以要分层，要分离不同的关注点。在不同的层面上去关注不同的具体的事情。

一句话来衡量: *设计就是让一个看起来不太可能能做好的东西变的很显然能做好*

* 如何设计

** 原始需求分析
划重点: 不关心系统，不关心当前是什么样，不关心有哪些模块。只关心一点:  *系统对外体现是什么样*. (对外并不仅仅指对外的用户视图。只要是外部能观测到的，都是系统的对外体现)

这一阶段，关注的就是系统整体对外的承诺。到底要做什么。

- 拼团案例 [[拼团需求分析]]

** 用户场景 && 场景分析
这一步，主要目的是把对外承诺细化。看看会有哪些不同的流程, 不同的场景。

常见的分析方法就是: 有哪些用户，哪些角色，分别关注哪些数据，数据流或者操作流大约是是什么样的。

比较常见的展示工具就是时序图了。

这一阶段, 关注的就是对外承诺的详细信息，对内会涉及到哪些场景和状态。从而可以分析出，内部需要哪些模块，如何配合。

- 拼团案例 [[拼团用户场景]]

** 系统概要设计
在这个阶段，主要的工作是，基于上文中的具体场景，分析出需要 *哪些模块* 来承载各自的功能，如何配合。

我认为，这个也是从需求到落实最关键的一步。因为在这里，需要划定 *模块的职责和边界*, 以及, 如何通过这些职责，组织出所需要的功能。

常见的分析方法也一样是，基于上文中的系统需要提供的功能，如何分解让各个模块配合实现。

PS: 模块的拆分是一个迭代的过程(玄学)，一般是先分，然后看模块间交互，然后调整。满意为止...

除了模块拆分以外，还有一些重点问题可以单独拿出来放在这个模块讨论。

- 拼团案例 [[拼团系统概要设计]]

** 模块内部设计
具体方法其实类似，但是需要更多考虑一点， *如何用内部不可见的存储/状态，去实现外部的行为或者感知* 。

- 拼团案例 [[拼团模块内部设计]]
** 任务分解
在这里，更多是从一个这个业务需求的负责人角度，来看，需要哪些地方有工作，哪些工作，如何分解，如何跟踪。让整体的业务需求更可控。

- 拼团案例 [[拼团任务分解]]

* 案例分析
** 票务系统设计
   整体内容相对完善一些，供参考:
   [[http://git.pn.com/piaoniu/piaoniu.wiki/blob/master/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3/ticket-system.pdf][票务系统设计文档下载]]


#+INCLUDE: "./pintuan.org" :minlevel 2

** 套票
***   TODO: 补充完成设计文档

